on: [push]
jobs:
  test:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - run: npm install
      - run: npm test
      - run: echo ${{ secrets.DOCKER_PWD }} | docker login -u ${{ secrets.DOCKER_LOGIN }} --password-stdin
      - run: docker build -t ${{ secrets.DOCKER_LOGIN }}/${{ secrets.DOCKER_REPO }}:${GITHUB_REF:11} -f Dockerfile .
      - run: docker push ${{ secrets.DOCKER_LOGIN }}/${{ secrets.DOCKER_REPO }}:${GITHUB_REF:11}
